### ISSUE TITLE
Failure with no output if test container does not have a running service

### ISSUE THREAD

**Issue by strazto** [adambirds/docker-compose-action#10]
For the following:

```yaml
name: E2E Test Stack
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on:
      - self-hosted
      - builder
    steps:
    - uses: actions/checkout@v3
    - uses: adambirds/docker-compose-action@v1.3.0
      env:
        # Isolate different compose projects
        COMPOSE_PROJECT_NAME: "e2e-${{ github.run_id }}"
      with:
        compose-file: |
          docker-compose.no-bind.yaml
          docker-compose.e2e.yaml
        test-container: playwright
        test-command: npm run 'test:e2e'

```

I get the following logs (after creating the whole stack incl. the playwright container)

```
compose started
testContainer playwright
testCommand npm run 'test:e2e'
Error: tests failed {"exitCode":1,"err":"","out":""}
```

playwright dockerfile:

```dockerfile
FROM mcr.microsoft.com/playwright:v1.44.1-jammy

WORKDIR /app
ADD package.json package-lock.json .

RUN npm ci

ADD playwright.config.ts .
ADD tests ./tests

```

```yaml
# docker-compose.e2e.yaml

services:
    playwright:
      #image: mcr.microsoft.com/playwright:v1.44.1-jammy
      build:
        context: .
        dockerfile: ./Dockerfile.playwright
```

I suspect its because you use docker.exec for running the test command, and my playwright container doesn't have an ongoing entrypoint, so terminates immediately.

https://github.com/adambirds/docker-compose-action/blob/cf2e51f76beacad15b1046de89ee2eb22ea70bac/main.js#L42 

the test container should not be required to have a running entry point IMO, maybe can use `.run` instead or allow config to allow `.run`
