### ISSUE TITLE
Error: compose up failed ENOENT

### ISSUE THREAD

**Issue by ramonesteban78** [adambirds/docker-compose-action#12]
My pipeline was working fine but suddenly it started to fail with:

Error: compose up failed {"errno":-2,"code":"ENOENT","syscall":"spawn docker-compose","path":"docker-compose","spawnargs":["-f","./docker-compose.yml","up","-d","mongo","metagigs-server"]}

This is how I'm defining the task:
```yaml
      - name: Deploy docker-compose and Run server tests
        uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "./docker-compose.yml"
          services: |
            mongo
            metagigs-server
          test-container: "metagigs-server"
          test-command: "./mbt alltests"
```

The docker compose file is located in the root folder of the repo and its name is `docker-compose.yml`
Any ideas of why is this happening?
