### ISSUE TITLE
Update compose & run v2 of compose

### ISSUE THREAD

**Issue by strazto** [adambirds/docker-compose-action#9]
The current version of `docker-compose` is 0.23.5 : 
 
https://github.com/adambirds/docker-compose-action/blob/cf2e51f76beacad15b1046de89ee2eb22ea70bac/package.json#L18 

<details><summary>Nevermind, it was actually the docker-compose binary on my runner</summary>

This version only supports the `docker-compose` `v1` spec.

The latest version of the npm docker-compose supports `v2`, since [v0.24.0](https://github.com/PDMLab/docker-compose/blob/master/CHANGELOG.md#0240-2023-04-28)

The compose spec added https://github.com/compose-spec/compose-spec/pull/340 a yaml tag for resetting values in an override, for example

```yaml
# docker-compose.base.yaml
services:
    db:
        # ... 
        build:
            context: db
        ports:
            - "5432:5432" 
        volumes:
            - aggregator-data:/var/lib/postgresql/data
```

```yaml
# docker-compose.e2e.yaml
services:
    playwright:
      build:
        context: .
        dockerfile: ./Dockerfile.playwright
    # Disable ports
    db:
      ports: !reset []
      volumes: !reset []
```

This is useful in CI, as I want to use my compose stack to run e2e tests, and disable portforwarding + persistence so I can run multiple compose stacks in parallel on the same runner, ie:

```yaml
name: E2E Test Stack
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on:
      - self-hosted
      - builder
    steps:
    - uses: actions/checkout@v3
    - uses: adambirds/docker-compose-action@v1.3.0
      env:
        # Isolate different compose projects
        COMPOSE_PROJECT_NAME: "e2e-${{ github.run_id }}"
      with:
        compose-file: |
          docker-compose.base.yaml
          docker-compose.e2e.yaml
        test-container: playwright
        test-command: npx playwright test
```

Note that in the above, I disabled concurrency within the same branch, but the workflow may run concurrently for different branches.

Currently, I get the following error:

```
compose up failed {"exitCode":1,"err":"yaml.constructor.ConstructorError: could not determine a constructor for the tag '!reset'\n  in \"./docker-compose.e2e.yaml\", line 10, column 14\n","out":""}
```

I believe that using (or allowing) the v2 bindings may allow us to use new feature from the spec

</details>

Update - This can run `docker-compose` v2, however, the machine running this needs to alias `docker-compose` to the plugin binary. 

A good enough way is to symlink it, https://stackoverflow.com/a/76909275/9238801

```bash
ln -f -s /usr/libexec/docker/cli-plugins/docker-compose /usr/local/bin/docker-compose
```
